---
title: "Home"
---

<style> h1 {font-size: 1.3em; margin-bottom: 1em;} </style>

# Transparent Statistics in Human–Computer Interaction

Transparent statistics is a philosophy of statistical reporting whose purpose is scientific advancement rather than persuasion. We are interested in moving the field of <abbr title="Human-Computer Interaction">HCI</abbr> and related fields like visualization towards clearer and more reliable ways of writing about experiments.

We organize events at the [ACM CHI](chi) and [IEEE VIS](vis) conferences related to research transparency.

To learn about transparent statistics, check out the **[Transparent Statistics Guidelines](https://transparentstats.github.io/guidelines/)**

### Join our Slack
The best way to get involved is via slack. [Email us](core@transparentstatistics.org), and we'll send you an invite.  
We also have a [mailing list](https://groups.google.com/d/forum/transparent-stats-hci), but the Slack is more active.

### Organizers
Fanny Chevalier, Lewis Chuang, Pierre Dragicevic, Shion Guha, Steve Haroz, Matthew Kay, and Chat Wacharamanotham
