---
title: "Workshop: Moving Transparent Statistics Forward @CHI 2017"
date: "2017-01-01"
---

_[Matthew Kay](http://mjskay.com/), [Steve Haroz](http://steveharoz.com/), [Shion Guha](https://www.cs.cornell.edu/~sguha/), [Pierre Dragicevic](https://www.lri.fr/~dragice/), and [Chat Wacharamanotham](http://zpac.ch/chat)_

This workshop produced the intial draft of the [Transparent Statistics Guidelines for <abbr title="Human-Computer Interaction">HCI</abbr>](https://transparentstats.github.io/guidelines/).

The original <abbr title="Call for Participation">CFP</abbr> for the workshop is below, and position papers from workshop participants are available [here](https://drive.google.com/drive/folders/0B8SF-zy_7oe9TXhCQlVJWkc0azg).


### Call for Participation – Deadline Feb 15  
Workshop at [CHI 2017](https://chi2017.acm.org/workshops.html), Saturday, May 6, 2017

<abbr title="Human-Computer Interaction">HCI</abbr> is large and multidisciplinary, drawing on a variety of statistical practices. However, many of these existing practices have drawn increasing criticism within both <abbr>HCI</abbr> and related fields, including but not limited to: over-reliance on particular statistical methods, a lack of transparent reporting, a lack of replication and meta-analysis, few studies published with data or study materials, and inadequate education in statistics. These issues have even reached the popular press in coverage of the _replication crisis_ in social science.

We are running a _working_ workshop to develop concrete guidelines for improving statistical practice in <abbr>HCI</abbr>. Participants will work in groups to flesh out guidelines for helping reviewers fairly assess statistical reports in <abbr title="Confence on Human Factors in Computing Systems">CHI</abbr> papers, concrete suggestions for changes to review processes, resources for authors, and other relevant guidelines or proposals the group wishes to advance. We will seed writing with draft guidelines developed in the wake of last years’ [<abbr title="Special Interest Group">SIG</abbr> on Transparent Statistics in <abbr>HCI</abbr>](/chi2016). However, we will not be constrained to the outline in these draft documents if discussions take us elsewhere.

These documents will be shared publicly once finalized and we will engage the <abbr>CHI</abbr> Executive Committee and/or Program Chairs to discuss the feasibility of suggested changes to the review process, and the possibility of incorporating some of the recommendations into official documents like the <abbr title="Special Interest Group on Computer-Human Interaction">SIGCHI</abbr> reviewer guidelines. We will also continue hosting and drafting future revisions of the documents on a collaborative editing platform.

**We are looking for a diverse set of perspectives on quantitative methods** in the <abbr>HCI</abbr> community to develop these documents (while qualitative methods are important to <abbr>HCI</abbr>, our primary focus in this workshop is on improving the use and communication of quantitative work). If you are interested in improving the state of statistical practice in <abbr>HCI</abbr>—whether or not you attended last year’s SIG—submit a position statement (at most 2 pages in [<abbr>CHI</abbr> Extended Abstracts format](https://chi2017.acm.org/submission-formats.html)) containing:

*   A short Bio (If there are multiple authors, only include a bio for the one author who wishes to attend).
*   A statement of special areas of interest (in <abbr>HCI</abbr>, methods, statistics and/or statistical reporting).
*   A position statement on improving statistical communication or practice or a comment on our [statement on transparent statistics from <abbr>CHI</abbr> 2016.](/chi2016)
*   An indication of which artifact(s) you are interested in contributing to from our [draft documents](http://tinyurl.com/transparent-stats-docs), or a suggestion for another artifact you believe should be included at the workshop.

**Submit to [chi2017workshop@transparentstatistics.org](mailto:chi2017workshop@transparentstatistics.org)**. The final deadline for submission is **Feb 15, 2017**.

As much as we would like as many <abbr>CHI</abbr> researchers as possible to get involved in this initiative, we may not be able to accept all applicants due to limits in the number of attendees at <abbr>CHI</abbr> workshops. If this happens, we will select applications based on expertise, diversity of perspectives in quantitative methods, diversity of <abbr>HCI</abbr> domains, and diversity of interest in specific artifacts (to ensure we have people interested in working on each artifact). **Our goal is that the participants reflect the diversity in quantitative methods, statistics, and domains across HCI.**

The purpose of the position statement is to help us determine _specific_ participants, so **we encourage one author per position statement**. Position statements with multiple authors should clearly indicate which author will attend. If your position statement is accepted, the attending author must register for both the workshop and at least one day of the conference.

